#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

define('PHP_SAAS_SCRIPT_ROOT', dirname(realpath(__FILE__)));

$app = new Symfony\Component\Console\Application('PHP-SaaS', '0.7.0');
$app->add(new PHPSaaS\PHPSaaS\DevCommand);
$app->add(new PHPSaaS\PHPSaaS\NewCommand);

$app->run();
