#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

define('SCRIPT_ROOT', dirname(realpath(__FILE__)));

$app = new Symfony\Component\Console\Application('PHP-SaaS', '0.1.0');
$app->add(new PHPSaaS\PHPSaaS\DevCommand);
$app->add(new PHPSaaS\PHPSaaS\NewCommand);

$app->run();
